name = "game-trade-hub-worker"
main = "worker/src/index.ts"
compatibility_date = "2024-05-02"

[assets]
directory = "admin"

[vars]
# RAPIDAPI_KEY = "скопируйте ключ RapidAPI"
# TELEGRAM_BOT_TOKEN = "токен бота для уведомлений"

[[d1_databases]]
binding = "DB"
database_name = "game-trade-hub"
database_id = "218d8c96-72e7-4cb6-bc1c-0acfefbf99fd"

[ai]
binding = "AI"
model = "@cf/meta/m2m100-1.2b"
